sudo: false
language: node_js
services:
- mysql
- mongodb
- redis-server
node_js:
- '6'
- '5'
- '4'
- '3'
- '2'
- '1'
- '0.12'
- '0.10'
notifications:
  slack:
    rooms:
      secure: k+Ky/oNWErqCODqov6N22P3buYg0hqVTUO3FLp/cbrq9KAcef0EKFCPqyjr0izKkN6xt3NLI4DYOI4IVv24+n3GtdUiSQTq+s6Y0wnbjLnu4pc/BRvdWh4aJR4KBSH22CsZ33GxhAUDFW8Xkv47L8dl3k9MKmlZaLXh3mF1pinY=
    on_success: change
    on_failure: change
    on_pull_requests: false
